/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as VerhaalRouteImport } from './routes/verhaal'
import { Route as VoorwaardenRouteImport } from './routes/voorwaarden'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedBerichtenRouteImport } from './routes/_authenticated/berichten'
import { Route as AuthenticatedDeployRouteImport } from './routes/_authenticated/deploy'
import { Route as AuthenticatedFeedRouteImport } from './routes/_authenticated/feed'
import { Route as AuthenticatedInstellingenRouteImport } from './routes/_authenticated/instellingen'
import { Route as AuthenticatedLedenRouteImport } from './routes/_authenticated/leden'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedChatsIndexRouteImport } from './routes/_authenticated/chats.index'
import { Route as AuthenticatedChatsIdRouteImport } from './routes/_authenticated/chats.$id'
import { Route as AuthenticatedProfielIdRouteImport } from './routes/_authenticated/profiel.$id'
import { Route as AuthenticatedWaagjeIdRouteImport } from './routes/_authenticated/waagje.$id'
import { Route as AuthenticatedWaagjeNieuwRouteImport } from './routes/_authenticated/waagje.nieuw'
import { Route as ApiPublicDoneerRouteImport } from './routes/api/public/doneer'
import { Route as ApiPublicImportUitagendaRouteImport } from './routes/api/public/import-uitagenda'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const VerhaalRoute = VerhaalRouteImport.update({
  id: '/verhaal',
  path: '/verhaal',
  getParentRoute: () => rootRouteImport,
} as any)
const VoorwaardenRoute = VoorwaardenRouteImport.update({
  id: '/voorwaarden',
  path: '/voorwaarden',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBerichtenRoute = AuthenticatedBerichtenRouteImport.update({
  id: '/berichten',
  path: '/berichten',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDeployRoute = AuthenticatedDeployRouteImport.update({
  id: '/deploy',
  path: '/deploy',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFeedRoute = AuthenticatedFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInstellingenRoute =
  AuthenticatedInstellingenRouteImport.update({
    id: '/instellingen',
    path: '/instellingen',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLedenRoute = AuthenticatedLedenRouteImport.update({
  id: '/leden',
  path: '/leden',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatsIdRoute = AuthenticatedChatsIdRouteImport.update({
  id: '/chats/$id',
  path: '/chats/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfielIdRoute = AuthenticatedProfielIdRouteImport.update({
  id: '/profiel/$id',
  path: '/profiel/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWaagjeIdRoute = AuthenticatedWaagjeIdRouteImport.update({
  id: '/waagje/$id',
  path: '/waagje/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWaagjeNieuwRoute =
  AuthenticatedWaagjeNieuwRouteImport.update({
    id: '/waagje/nieuw',
    path: '/waagje/nieuw',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicDoneerRoute = ApiPublicDoneerRouteImport.update({
  id: '/api/public/doneer',
  path: '/api/public/doneer',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicImportUitagendaRoute =
  ApiPublicImportUitagendaRouteImport.update({
    id: '/api/public/import-uitagenda',
    path: '/api/public/import-uitagenda',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cookies': typeof CookiesRoute
  '/disclaimer': typeof DisclaimerRoute
  '/privacy': typeof PrivacyRoute
  '/verhaal': typeof VerhaalRoute
  '/voorwaarden': typeof VoorwaardenRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/berichten': typeof AuthenticatedBerichtenRoute
  '/deploy': typeof AuthenticatedDeployRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/instellingen': typeof AuthenticatedInstellingenRoute
  '/leden': typeof AuthenticatedLedenRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/chats/$id': typeof AuthenticatedChatsIdRoute
  '/profiel/$id': typeof AuthenticatedProfielIdRoute
  '/waagje/$id': typeof AuthenticatedWaagjeIdRoute
  '/waagje/nieuw': typeof AuthenticatedWaagjeNieuwRoute
  '/api/public/doneer': typeof ApiPublicDoneerRoute
  '/api/public/import-uitagenda': typeof ApiPublicImportUitagendaRoute
  '/chats/': typeof AuthenticatedChatsIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cookies': typeof CookiesRoute
  '/disclaimer': typeof DisclaimerRoute
  '/privacy': typeof PrivacyRoute
  '/verhaal': typeof VerhaalRoute
  '/voorwaarden': typeof VoorwaardenRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/berichten': typeof AuthenticatedBerichtenRoute
  '/deploy': typeof AuthenticatedDeployRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/instellingen': typeof AuthenticatedInstellingenRoute
  '/leden': typeof AuthenticatedLedenRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/chats/$id': typeof AuthenticatedChatsIdRoute
  '/profiel/$id': typeof AuthenticatedProfielIdRoute
  '/waagje/$id': typeof AuthenticatedWaagjeIdRoute
  '/waagje/nieuw': typeof AuthenticatedWaagjeNieuwRoute
  '/api/public/doneer': typeof ApiPublicDoneerRoute
  '/api/public/import-uitagenda': typeof ApiPublicImportUitagendaRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/cookies': typeof CookiesRoute
  '/disclaimer': typeof DisclaimerRoute
  '/privacy': typeof PrivacyRoute
  '/verhaal': typeof VerhaalRoute
  '/voorwaarden': typeof VoorwaardenRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/berichten': typeof AuthenticatedBerichtenRoute
  '/_authenticated/deploy': typeof AuthenticatedDeployRoute
  '/_authenticated/feed': typeof AuthenticatedFeedRoute
  '/_authenticated/instellingen': typeof AuthenticatedInstellingenRoute
  '/_authenticated/leden': typeof AuthenticatedLedenRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/chats/$id': typeof AuthenticatedChatsIdRoute
  '/_authenticated/profiel/$id': typeof AuthenticatedProfielIdRoute
  '/_authenticated/waagje/$id': typeof AuthenticatedWaagjeIdRoute
  '/_authenticated/waagje/nieuw': typeof AuthenticatedWaagjeNieuwRoute
  '/api/public/doneer': typeof ApiPublicDoneerRoute
  '/api/public/import-uitagenda': typeof ApiPublicImportUitagendaRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cookies'
    | '/disclaimer'
    | '/privacy'
    | '/verhaal'
    | '/voorwaarden'
    | '/admin'
    | '/berichten'
    | '/deploy'
    | '/feed'
    | '/instellingen'
    | '/leden'
    | '/onboarding'
    | '/chats/$id'
    | '/profiel/$id'
    | '/waagje/$id'
    | '/waagje/nieuw'
    | '/api/public/doneer'
    | '/api/public/import-uitagenda'
    | '/chats/'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cookies'
    | '/disclaimer'
    | '/privacy'
    | '/verhaal'
    | '/voorwaarden'
    | '/admin'
    | '/berichten'
    | '/deploy'
    | '/feed'
    | '/instellingen'
    | '/leden'
    | '/onboarding'
    | '/chats/$id'
    | '/profiel/$id'
    | '/waagje/$id'
    | '/waagje/nieuw'
    | '/api/public/doneer'
    | '/api/public/import-uitagenda'
    | '/chats'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/cookies'
    | '/disclaimer'
    | '/privacy'
    | '/verhaal'
    | '/voorwaarden'
    | '/_authenticated/admin'
    | '/_authenticated/berichten'
    | '/_authenticated/deploy'
    | '/_authenticated/feed'
    | '/_authenticated/instellingen'
    | '/_authenticated/leden'
    | '/_authenticated/onboarding'
    | '/_authenticated/chats/$id'
    | '/_authenticated/profiel/$id'
    | '/_authenticated/waagje/$id'
    | '/_authenticated/waagje/nieuw'
    | '/api/public/doneer'
    | '/api/public/import-uitagenda'
    | '/_authenticated/chats/'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CookiesRoute: typeof CookiesRoute
  DisclaimerRoute: typeof DisclaimerRoute
  PrivacyRoute: typeof PrivacyRoute
  VerhaalRoute: typeof VerhaalRoute
  VoorwaardenRoute: typeof VoorwaardenRoute
  ApiPublicDoneerRoute: typeof ApiPublicDoneerRoute
  ApiPublicImportUitagendaRoute: typeof ApiPublicImportUitagendaRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verhaal': {
      id: '/verhaal'
      path: '/verhaal'
      fullPath: '/verhaal'
      preLoaderRoute: typeof VerhaalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voorwaarden': {
      id: '/voorwaarden'
      path: '/voorwaarden'
      fullPath: '/voorwaarden'
      preLoaderRoute: typeof VoorwaardenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/berichten': {
      id: '/_authenticated/berichten'
      path: '/berichten'
      fullPath: '/berichten'
      preLoaderRoute: typeof AuthenticatedBerichtenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/deploy': {
      id: '/_authenticated/deploy'
      path: '/deploy'
      fullPath: '/deploy'
      preLoaderRoute: typeof AuthenticatedDeployRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/feed': {
      id: '/_authenticated/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AuthenticatedFeedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/instellingen': {
      id: '/_authenticated/instellingen'
      path: '/instellingen'
      fullPath: '/instellingen'
      preLoaderRoute: typeof AuthenticatedInstellingenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leden': {
      id: '/_authenticated/leden'
      path: '/leden'
      fullPath: '/leden'
      preLoaderRoute: typeof AuthenticatedLedenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats/'
      preLoaderRoute: typeof AuthenticatedChatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chats/$id': {
      id: '/_authenticated/chats/$id'
      path: '/chats/$id'
      fullPath: '/chats/$id'
      preLoaderRoute: typeof AuthenticatedChatsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profiel/$id': {
      id: '/_authenticated/profiel/$id'
      path: '/profiel/$id'
      fullPath: '/profiel/$id'
      preLoaderRoute: typeof AuthenticatedProfielIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/waagje/$id': {
      id: '/_authenticated/waagje/$id'
      path: '/waagje/$id'
      fullPath: '/waagje/$id'
      preLoaderRoute: typeof AuthenticatedWaagjeIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/waagje/nieuw': {
      id: '/_authenticated/waagje/nieuw'
      path: '/waagje/nieuw'
      fullPath: '/waagje/nieuw'
      preLoaderRoute: typeof AuthenticatedWaagjeNieuwRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/doneer': {
      id: '/api/public/doneer'
      path: '/api/public/doneer'
      fullPath: '/api/public/doneer'
      preLoaderRoute: typeof ApiPublicDoneerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/import-uitagenda': {
      id: '/api/public/import-uitagenda'
      path: '/api/public/import-uitagenda'
      fullPath: '/api/public/import-uitagenda'
      preLoaderRoute: typeof ApiPublicImportUitagendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedBerichtenRoute: typeof AuthenticatedBerichtenRoute
  AuthenticatedDeployRoute: typeof AuthenticatedDeployRoute
  AuthenticatedFeedRoute: typeof AuthenticatedFeedRoute
  AuthenticatedInstellingenRoute: typeof AuthenticatedInstellingenRoute
  AuthenticatedLedenRoute: typeof AuthenticatedLedenRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedChatsIdRoute: typeof AuthenticatedChatsIdRoute
  AuthenticatedProfielIdRoute: typeof AuthenticatedProfielIdRoute
  AuthenticatedWaagjeIdRoute: typeof AuthenticatedWaagjeIdRoute
  AuthenticatedWaagjeNieuwRoute: typeof AuthenticatedWaagjeNieuwRoute
  AuthenticatedChatsIndexRoute: typeof AuthenticatedChatsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedBerichtenRoute: AuthenticatedBerichtenRoute,
  AuthenticatedDeployRoute: AuthenticatedDeployRoute,
  AuthenticatedFeedRoute: AuthenticatedFeedRoute,
  AuthenticatedInstellingenRoute: AuthenticatedInstellingenRoute,
  AuthenticatedLedenRoute: AuthenticatedLedenRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedChatsIdRoute: AuthenticatedChatsIdRoute,
  AuthenticatedProfielIdRoute: AuthenticatedProfielIdRoute,
  AuthenticatedWaagjeIdRoute: AuthenticatedWaagjeIdRoute,
  AuthenticatedWaagjeNieuwRoute: AuthenticatedWaagjeNieuwRoute,
  AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CookiesRoute: CookiesRoute,
  DisclaimerRoute: DisclaimerRoute,
  PrivacyRoute: PrivacyRoute,
  VerhaalRoute: VerhaalRoute,
  VoorwaardenRoute: VoorwaardenRoute,
  ApiPublicDoneerRoute: ApiPublicDoneerRoute,
  ApiPublicImportUitagendaRoute: ApiPublicImportUitagendaRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
